baseURL = 'https://walt3r.dev/'
languageCode = 'en-us'
title = 'walt3r.dev'
theme = 'hugo-book'
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/waltervargas"
  weight = 10

[[menu.after]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/walterve/"
  weight = 20

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'
  BookSearch = true
  BookToC = true
  BookSection = 'docs'
  BookRepo = 'https://github.com/waltervargas/walt3r.dev'
  BookCommitPath = 'commit'
  BookDateFormat = 'Jan 2, 2006'
